/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn generate` to regenerate this file.
 */
export interface IMAGE {
  height?: number;
  id?: string;
  url?: string;
  width?: number;
  _id?: string;
}
export interface WEIGHT {
  imperial?: string;
  metric?: string;
  _id?: string;
}
export interface Breeds {
  createBy?: string;
  creator?: User;
  updateBy?: string;
  updator?: User;
  _id?: string;
  updatedAt?: number;
  createdAt?: number;
  adaptability?: number;
  affection_level?: number;
  alt_names?: string;
  child_friendly?: number;
  country_code?: string;
  country_codes?: string;
  description?: string;
  dog_friendly?: number;
  energy_level?: number;
  experimental?: number;
  grooming?: number;
  hairless?: number;
  health_issues?: number;
  hypoallergenic?: number;
  id?: string;
  image?: IMAGE;
  indoor?: number;
  intelligence?: number;
  life_span?: string;
  name?: string;
  natural?: number;
  origin?: string;
  rare?: number;
  reference_image_id?: string;
  rex?: number;
  shedding_level?: number;
  short_legs?: number;
  social_needs?: number;
  stranger_friendly?: number;
  suppressed_tail?: number;
  temperament?: string;
  vetstreet_url?: string;
  vocalisation?: number;
  weight?: WEIGHT;
  wikipedia_url?: string;
}
export interface WEIGHT {
  imperial?: string;
  metric?: string;
  _id?: string;
}
export interface IMAGE {
  height?: number;
  id?: string;
  url?: string;
  width?: number;
  _id?: string;
}
export interface NFT {
  nftId?: string;
  status?: "pending" | "fail" | "success";
  _id?: string;
}
