version: "3.6"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo:/data/db
    networks:
      - codeleap
  nats:
    image: nats:1.3.0-linux
    container_name: nats
    restart: always
    ports:
      - 4222:4222
      - 4444:4444
      - 6222:6222
      - 8222:8222
    networks:
      - codeleap

  redis:
    image: redis:5-alpine
    container_name: redis5
    hostname: redis5
    restart: always
    ports:
      - 6379:6379
    networks:
      - codeleap
volumes:
  mongo:

networks:
  codeleap:
    external: true
    driver: bridge
